apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-notready-test
spec:
  replicas: 1
  selector:
    matchLabels:
      test-deployment: course-app-notready-test
  template:
    metadata:
      labels:
        app: course-app
        test-deployment: course-app-notready-test
    spec:
      containers:
        - name: course-app
          image: iphilippenko/course-app:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: APP_STORE
              value: "redis"
            - name: APP_REDIS_URL
              value: "redis://redis-broken:6379/0"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5